name: my_places
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^0.5.2
  mobx: ^1.0.2
  flutter_mobx: ^1.0.1
  moor_flutter: ^2.1.1
  image_picker: ^0.6.3+4
  google_maps_flutter: ^0.5.24+1
  geocoder: ^0.2.1
  flutter_rating_bar: ^3.0.1+1
  connectivity: ^0.4.8+1
  location: ^2.5.3
  geolocator: ^5.3.0
  path_provider: ^1.6.5
  nanoid: ^0.1.0
  permission_handler: ^4.4.0+hotfix.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  build_runner: any
  mobx_codegen: ^1.0.2
  moor_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/imagePlaceholder.png
    - assets/images/selectImagePlaceholder.png